modulelist=com.p6spy.engine.spy.P6SpyFactory
logMessageFormat=com.p6spy.engine.spy.appender.CustomLineFormat
customLogMessageFormat=%(currentTime) | %(executionTime) ms | %(category) | connection %(connectionId) | %(sqlSingleLine)
appender=com.p6spy.engine.spy.appender.StdoutLogger
useprefix=true
excludecategories=info,debug,result,resultset
