-- 为已有库补全表注释与字段注释（可重复执行）
USE `nova_mall`;

-- ========== 表注释 ==========
ALTER TABLE `sys_user` COMMENT='系统用户表（后台管理员与C端会员共用）';
ALTER TABLE `sys_role` COMMENT='系统角色表';
ALTER TABLE `sys_permission` COMMENT='系统权限/菜单表';
ALTER TABLE `sys_user_role` COMMENT='用户-角色关联表';
ALTER TABLE `sys_role_permission` COMMENT='角色-权限关联表';
ALTER TABLE `sys_oper_log` COMMENT='系统操作日志表';
ALTER TABLE `sys_config` COMMENT='系统参数配置表';
ALTER TABLE `mall_goods_category` COMMENT='商品分类表';
ALTER TABLE `mall_goods` COMMENT='商品表';
ALTER TABLE `mall_goods_comment` COMMENT='商品评价表';
ALTER TABLE `mall_cart` COMMENT='购物车表';

-- ========== sys_user ==========
ALTER TABLE `sys_user`
  MODIFY COLUMN `id` INT NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  MODIFY COLUMN `user_name` VARCHAR(64) NOT NULL COMMENT '登录用户名',
  MODIFY COLUMN `password` VARCHAR(128) NOT NULL COMMENT '密码（BCrypt）',
  MODIFY COLUMN `user_real_name` VARCHAR(64) DEFAULT NULL COMMENT '真实姓名/昵称',
  MODIFY COLUMN `phone` VARCHAR(20) DEFAULT NULL COMMENT '手机号',
  MODIFY COLUMN `email` VARCHAR(128) DEFAULT NULL COMMENT '邮箱',
  MODIFY COLUMN `avatar` VARCHAR(512) DEFAULT NULL COMMENT '头像URL',
  MODIFY COLUMN `user_flag` TINYINT NOT NULL DEFAULT 2 COMMENT '用户标识：1内部 2管理员 3普通用户',
  MODIFY COLUMN `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1正常 0禁用',
  MODIFY COLUMN `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是',
  MODIFY COLUMN `remark` VARCHAR(255) DEFAULT NULL COMMENT '备注',
  MODIFY COLUMN `create_time` BIGINT DEFAULT NULL COMMENT '创建时间（毫秒时间戳）',
  MODIFY COLUMN `update_time` BIGINT DEFAULT NULL COMMENT '更新时间（毫秒时间戳）',
  MODIFY COLUMN `create_user` INT DEFAULT NULL COMMENT '创建人用户ID',
  MODIFY COLUMN `update_user` INT DEFAULT NULL COMMENT '更新人用户ID';

-- ========== sys_role ==========
ALTER TABLE `sys_role`
  MODIFY COLUMN `id` INT NOT NULL AUTO_INCREMENT COMMENT '角色ID',
  MODIFY COLUMN `role_code` VARCHAR(64) NOT NULL COMMENT '角色编码',
  MODIFY COLUMN `role_name` VARCHAR(64) NOT NULL COMMENT '角色名称',
  MODIFY COLUMN `sort` INT DEFAULT 0 COMMENT '排序（越小越靠前）',
  MODIFY COLUMN `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1正常 0禁用',
  MODIFY COLUMN `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是',
  MODIFY COLUMN `remark` VARCHAR(255) DEFAULT NULL COMMENT '备注',
  MODIFY COLUMN `create_time` BIGINT DEFAULT NULL COMMENT '创建时间（毫秒时间戳）',
  MODIFY COLUMN `update_time` BIGINT DEFAULT NULL COMMENT '更新时间（毫秒时间戳）',
  MODIFY COLUMN `create_user` INT DEFAULT NULL COMMENT '创建人用户ID',
  MODIFY COLUMN `update_user` INT DEFAULT NULL COMMENT '更新人用户ID';

-- ========== sys_permission ==========
ALTER TABLE `sys_permission`
  MODIFY COLUMN `id` INT NOT NULL AUTO_INCREMENT COMMENT '权限/菜单ID',
  MODIFY COLUMN `parent_id` INT NOT NULL DEFAULT 0 COMMENT '父级ID，0为顶级',
  MODIFY COLUMN `name` VARCHAR(64) NOT NULL COMMENT '菜单/权限名称',
  MODIFY COLUMN `type` TINYINT NOT NULL DEFAULT 1 COMMENT '类型：1目录 2菜单 3按钮',
  MODIFY COLUMN `path` VARCHAR(128) DEFAULT NULL COMMENT '路由路径',
  MODIFY COLUMN `component` VARCHAR(128) DEFAULT NULL COMMENT '前端组件路径',
  MODIFY COLUMN `perms` VARCHAR(128) DEFAULT NULL COMMENT '权限标识，如 system:user:list',
  MODIFY COLUMN `icon` VARCHAR(64) DEFAULT NULL COMMENT '菜单图标',
  MODIFY COLUMN `sort` INT DEFAULT 0 COMMENT '排序（越小越靠前）',
  MODIFY COLUMN `visible` TINYINT NOT NULL DEFAULT 1 COMMENT '是否可见：1是 0否',
  MODIFY COLUMN `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1正常 0禁用',
  MODIFY COLUMN `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是',
  MODIFY COLUMN `create_time` BIGINT DEFAULT NULL COMMENT '创建时间（毫秒时间戳）',
  MODIFY COLUMN `update_time` BIGINT DEFAULT NULL COMMENT '更新时间（毫秒时间戳）',
  MODIFY COLUMN `create_user` INT DEFAULT NULL COMMENT '创建人用户ID',
  MODIFY COLUMN `update_user` INT DEFAULT NULL COMMENT '更新人用户ID';

-- ========== sys_user_role ==========
ALTER TABLE `sys_user_role`
  MODIFY COLUMN `id` INT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  MODIFY COLUMN `user_id` INT NOT NULL COMMENT '用户ID',
  MODIFY COLUMN `role_id` INT NOT NULL COMMENT '角色ID';

-- ========== sys_role_permission ==========
ALTER TABLE `sys_role_permission`
  MODIFY COLUMN `id` INT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  MODIFY COLUMN `role_id` INT NOT NULL COMMENT '角色ID',
  MODIFY COLUMN `permission_id` INT NOT NULL COMMENT '权限/菜单ID';

-- ========== sys_oper_log ==========
ALTER TABLE `sys_oper_log`
  MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '日志ID',
  MODIFY COLUMN `title` VARCHAR(64) DEFAULT NULL COMMENT '模块标题',
  MODIFY COLUMN `business_type` TINYINT DEFAULT 0 COMMENT '业务类型：0其它 1新增 2修改 3删除等',
  MODIFY COLUMN `method` VARCHAR(256) DEFAULT NULL COMMENT '方法名称',
  MODIFY COLUMN `request_method` VARCHAR(16) DEFAULT NULL COMMENT '请求方式（GET/POST等）',
  MODIFY COLUMN `oper_name` VARCHAR(64) DEFAULT NULL COMMENT '操作人员',
  MODIFY COLUMN `oper_url` VARCHAR(512) DEFAULT NULL COMMENT '请求URL',
  MODIFY COLUMN `oper_ip` VARCHAR(64) DEFAULT NULL COMMENT '操作IP',
  MODIFY COLUMN `oper_param` TEXT COMMENT '请求参数',
  MODIFY COLUMN `json_result` TEXT COMMENT '返回结果JSON',
  MODIFY COLUMN `status` TINYINT DEFAULT 1 COMMENT '操作状态：1成功 0失败',
  MODIFY COLUMN `error_msg` VARCHAR(2000) DEFAULT NULL COMMENT '错误消息',
  MODIFY COLUMN `cost_time` BIGINT DEFAULT 0 COMMENT '耗时（毫秒）',
  MODIFY COLUMN `oper_time` BIGINT DEFAULT NULL COMMENT '操作时间（毫秒时间戳）';

-- ========== sys_config ==========
ALTER TABLE `sys_config`
  MODIFY COLUMN `id` INT NOT NULL AUTO_INCREMENT COMMENT '配置ID',
  MODIFY COLUMN `config_key` VARCHAR(128) NOT NULL COMMENT '配置键',
  MODIFY COLUMN `config_value` VARCHAR(512) DEFAULT NULL COMMENT '配置值',
  MODIFY COLUMN `remark` VARCHAR(255) DEFAULT NULL COMMENT '备注说明',
  MODIFY COLUMN `create_time` BIGINT DEFAULT NULL COMMENT '创建时间（毫秒时间戳）',
  MODIFY COLUMN `update_time` BIGINT DEFAULT NULL COMMENT '更新时间（毫秒时间戳）',
  MODIFY COLUMN `create_user` INT DEFAULT NULL COMMENT '创建人用户ID',
  MODIFY COLUMN `update_user` INT DEFAULT NULL COMMENT '更新人用户ID';

-- ========== mall_goods_category ==========
ALTER TABLE `mall_goods_category`
  MODIFY COLUMN `id` INT NOT NULL AUTO_INCREMENT COMMENT '分类ID',
  MODIFY COLUMN `parent_id` INT NOT NULL DEFAULT 0 COMMENT '父分类ID，0为顶级',
  MODIFY COLUMN `name` VARCHAR(64) NOT NULL COMMENT '分类名称',
  MODIFY COLUMN `sort` INT DEFAULT 0 COMMENT '排序（越小越靠前）',
  MODIFY COLUMN `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用 0停用',
  MODIFY COLUMN `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是',
  MODIFY COLUMN `create_time` BIGINT DEFAULT NULL COMMENT '创建时间（毫秒时间戳）',
  MODIFY COLUMN `update_time` BIGINT DEFAULT NULL COMMENT '更新时间（毫秒时间戳）',
  MODIFY COLUMN `create_user` INT DEFAULT NULL COMMENT '创建人用户ID',
  MODIFY COLUMN `update_user` INT DEFAULT NULL COMMENT '更新人用户ID';

-- ========== mall_goods ==========
ALTER TABLE `mall_goods`
  MODIFY COLUMN `id` INT NOT NULL AUTO_INCREMENT COMMENT '商品ID',
  MODIFY COLUMN `category_id` INT DEFAULT NULL COMMENT '所属分类ID',
  MODIFY COLUMN `name` VARCHAR(128) NOT NULL COMMENT '商品名称',
  MODIFY COLUMN `sub_title` VARCHAR(255) DEFAULT NULL COMMENT '副标题/卖点',
  MODIFY COLUMN `detail` MEDIUMTEXT NULL COMMENT '商品详情（HTML/富文本）',
  MODIFY COLUMN `cover` VARCHAR(512) DEFAULT NULL COMMENT '封面图URL',
  MODIFY COLUMN `price` DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '优惠价/售价',
  MODIFY COLUMN `original_price` DECIMAL(10,2) DEFAULT NULL COMMENT '原价（划线价）',
  MODIFY COLUMN `stock` INT NOT NULL DEFAULT 0 COMMENT '库存数量',
  MODIFY COLUMN `sales` INT NOT NULL DEFAULT 0 COMMENT '销量',
  MODIFY COLUMN `status` TINYINT NOT NULL DEFAULT 1 COMMENT '上下架：1上架 0下架',
  MODIFY COLUMN `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是',
  MODIFY COLUMN `create_time` BIGINT DEFAULT NULL COMMENT '创建时间（毫秒时间戳）',
  MODIFY COLUMN `update_time` BIGINT DEFAULT NULL COMMENT '更新时间（毫秒时间戳）',
  MODIFY COLUMN `create_user` INT DEFAULT NULL COMMENT '创建人用户ID',
  MODIFY COLUMN `update_user` INT DEFAULT NULL COMMENT '更新人用户ID';

-- ========== mall_goods_comment ==========
ALTER TABLE `mall_goods_comment`
  MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '评价ID',
  MODIFY COLUMN `goods_id` INT NOT NULL COMMENT '商品ID',
  MODIFY COLUMN `user_id` INT NOT NULL COMMENT '评价用户ID',
  MODIFY COLUMN `user_name` VARCHAR(64) DEFAULT NULL COMMENT '评价用户昵称（冗余）',
  MODIFY COLUMN `star` TINYINT NOT NULL DEFAULT 5 COMMENT '星级：1-5',
  MODIFY COLUMN `content` VARCHAR(1000) NOT NULL COMMENT '评价内容',
  MODIFY COLUMN `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1显示 0隐藏',
  MODIFY COLUMN `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是',
  MODIFY COLUMN `create_time` BIGINT DEFAULT NULL COMMENT '创建时间（毫秒时间戳）',
  MODIFY COLUMN `update_time` BIGINT DEFAULT NULL COMMENT '更新时间（毫秒时间戳）',
  MODIFY COLUMN `create_user` INT DEFAULT NULL COMMENT '创建人用户ID',
  MODIFY COLUMN `update_user` INT DEFAULT NULL COMMENT '更新人用户ID';

-- ========== mall_cart ==========
ALTER TABLE `mall_cart`
  MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '购物车项ID',
  MODIFY COLUMN `user_id` INT NOT NULL COMMENT '用户ID',
  MODIFY COLUMN `goods_id` INT NOT NULL COMMENT '商品ID',
  MODIFY COLUMN `quantity` INT NOT NULL DEFAULT 1 COMMENT '购买数量',
  MODIFY COLUMN `checked` TINYINT NOT NULL DEFAULT 1 COMMENT '是否勾选结算：1是 0否',
  MODIFY COLUMN `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是',
  MODIFY COLUMN `create_time` BIGINT DEFAULT NULL COMMENT '创建时间（毫秒时间戳）',
  MODIFY COLUMN `update_time` BIGINT DEFAULT NULL COMMENT '更新时间（毫秒时间戳）',
  MODIFY COLUMN `create_user` INT DEFAULT NULL COMMENT '创建人用户ID',
  MODIFY COLUMN `update_user` INT DEFAULT NULL COMMENT '更新人用户ID';
